### ISSUE TITLE
Explore Blender Add-on

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#112]
As part of our efforts to get a working GUI for spritec, we are going to explore creating a Blender Add-on. The idea is to see what it takes to make one, get something simple working, and then see if we want to proceed in that direction. If we do decide to continue making an add-on, this issue will be closed and replaced with a number of other issues to continue the work on that add-on.

@daose will be doing the primary work on this starting next week with @sunjay helping as needed along the way.

## Resources

Blender Add-ons, Python

* https://docs.blender.org/manual/en/latest/advanced/scripting/addon_tutorial.html
* https://docs.blender.org/api/blender_python_api_current/info_overview.html
* https://docs.blender.org/api/blender_python_api_current/bpy.types.RenderEngine.html#bpy.types.RenderEngine
* https://docs.blender.org/api/blender_python_api_current/bpy.types.Panel.html#bpy.types.Panel
* Example add-on: https://github.com/sobotka/blender-addons/blob/master/ant_landscape/__init__.py
* https://wiki.blender.org/wiki/Process/Addons/Guidelines/metainfo
* https://realpython.com/python-type-checking/

Rust Python Bindings

* https://github.com/pyo3/pyo3#using-rust-from-python
* https://pyo3.rs/
* https://developers.redhat.com/blog/2017/11/16/speed-python-using-rust/
    * Article uses `cpython` crate which is what `pyo3` was forked from

### Notes
- example of blender plugin that references a dll: https://github.com/appleseedhq/blenderseed
- check out the examples in the text editor
- [panel example](https://docs.blender.org/api/current/info_quickstart.html#example-panel)
- [adding button to panel](https://docs.blender.org/api/current/bpy.types.UILayout.html#bpy.types.UILayout.operator)
- [adding preview to panel](https://docs.blender.org/api/current/bpy.types.UILayout.html#bpy.types.UILayout.template_preview)
- check out this addon: https://gitlab.com/integrity-sg/UltiMaze
- flow:
    - Use blender's [Image Editor](https://docs.blender.org/manual/en/latest/editors/image/index.html) to display images from spritec
     - Add a tab to the 3D viewport  (view, tool, item, spritec) that gives configuration, after pressing a button a new window pops up (set to the image editor) that displays the animation (rendered as individual poses with sequence suffix `pose001.png` saved in temp folder)
    - add a panel to properties render tab that offers some configuration (width/height, which animation to load), which sets the animation to view in the image editor.
    - can also show small previews in the panel itself
    - ~create a new space type~ (unable to do so from python)
    - draw the current viewport on top of view3d with opengl (think small preview in the corner)

### TODOs
- [ ] README.md for how to install and develop
- [ ] create python environment that force a version of python to be used (set it to same as blender)
- [ ] add flake8 checking
    - [ ] future: github action to validate flake8

**Comment by sunjay** [comment]
This has been completed! Thanks @daose for all your work! The verdict was to completely rule out Blender because the add-on API is too limited. We were not able to flexibly add a complete Editor Type for spritec. It was not worth investing in hacking around Blender's API just to get a subpar user experience.
