### ISSUE TITLE
Memory Efficient Scaling

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#26]
Our current approach to scaling is really naive. We have two buffers: one small and one big. To scale, we copy pixels from the small buffer into the larger buffer. To fill in the gaps, we copy each pixel from the small buffer into a small rectangle on the big buffer. This works and gives us the desired effect, but it can use a lot of extra memory for no reason in a lot of cases.

Maybe there is a way to do this better with just a single buffer?

https://github.com/ProtoArt/spritec/blob/9df6e0b23e2e425cc90cf2deddc4e1c9a73346ed/src/scale.rs#L16-L49

# Mentoring Instructions

Below are some options to explore. Feel free to try your own.

1. Implement a new `ScaledBuffer` type that works like `Buffer2d` in a lot of ways but specifically sets to a rectangle of pixels rather than just a single pixel
    * This saves on some memory and potentially makes us a tiny bit more performant because we don't have to do any copying after the fact (all pixels are scaled and applied immediately)
    * The `ScaledBuffer` type would have to implement the same traits as `Buffer2d` in order to work with `euc` (the shader library)
2. Use a more memory-efficient scaling algorithm: Instead of having two color buffers, one small and one big, have a single big color buffer. Render the image into the big color buffer using the small buffer’s size. Copy the colors from the pixels of the small buffer to their scaled up positions in the big buffer by going right-to-left, bottom-to-top. (Question: Does this algorithm actually work?)

Both of these solutions take about the same effort to implement.

To see which we should use, we should A) test them thoroughly in all kinds of cases with many different scale factors (0, 1, 2, etc.) and B) create a benchmark to see how this changes spritesheet/pose generation.

Benchmarking tutorial: https://bheisler.github.io/post/benchmarking-with-criterion-rs/
More on criterion-rs: https://github.com/bheisler/criterion.rs

To find cases where we scale buffers in our code, look at the `scale.rs` module and the places where its functions are used.

Please don't hesitate to ask me questions!

## To-Do

- [ ] Pixel colors should go directly to their destination buffer instead of an unscaled intermediary buffer in:
   - [ ] spritesheet generation (write directly to image)
   - [ ] pose generation (write directly to image)
   - [ ] GUI (write directly to final full-sized buffer)

**Comment by sunjay** [comment]
This is no longer relevant since we moved to OpenGL. #117 supersedes this issue.
